import { LitigationCase } from "./types";

export const initialCases: LitigationCase[] = [
  {
    id: "CASE-2023-001",
    caseInfo: {
      caseId: "CASE-2023-001",
      taxpayerName: "Nishat Fabrics & Mills Ltd",
      ntn: "1140294-7",
      strn: "0300114029411",
      taxPeriod: "Tax Year 2023",
      taxType: "PRA Sales Tax",
      relevantLegalSections: "Section 11, Section 52 of Punjab Sales Tax on Services Act 2012",
      authorityForum: "Punjab Revenue Authority (PRA)",
      documentType: "Show Cause Notice (SCN)",
      referenceNumber: "PRA-SCN-2023/1082",
      documentDate: "2023-11-15",
    },
    financialInfo: {
      taxDemand: 18500000, // 18.5M PKR
      penalty: 925000,     // 5% penalty
      defaultSurcharge: 1560000,
      refundAmount: 0,
      totalExposure: 20985000, // 20.9M
    },
    proceedingsInfo: {
      dateOfNotice: "2023-11-15",
      dateOfReply: "2023-12-10",
      hearingDates: ["2023-12-20", "2024-01-15", "2024-02-10"],
      orderDate: "2024-03-05",
      appealDate: "2024-04-02",
      decisionDate: "",
      currentStage: "Appeal Pending",
    },
    outcomeInfo: {
      departmentPosition: "Alleged non-withholding of sales tax on textile processing services and inputs from unregistered suppliers.",
      taxpayerPosition: "Services were rendered inside export-processing zones which are zero-rated; input tax withholding rules of FBR supersede. PRA lacks jurisdiction over federal inputs.",
      decisionSummary: "The PRA Deputy Commissioner confirmed the tax demand under ONO-41/2024 on March 5, 2024, rejecting export status exemptions.",
      reliefGranted: "No relief granted at original stage.",
      amountConfirmed: 18500000,
      amountDeleted: 0,
      amountRemanded: 0,
      currentStatus: "Active Appeal",
    },
    chronology: [
      {
        date: "2023-11-15",
        event: "Issue of Show Cause Notice",
        authority: "Deputy Commissioner (Appeals), PRA Lahore",
        referenceNo: "PRA-SCN-2023/1082",
        summary: "Notice alleging default on textile finishing services of PKR 18.5M.",
      },
      {
        date: "2023-12-10",
        event: "Filing of Detailed Reply",
        authority: "PRA Deputy Commissioner",
        referenceNo: "NFM-PRA/Reply-01",
        summary: "Taxpayer submitted detailed reply contesting charge based on zero-rating certificate.",
      },
      {
        date: "2024-01-15",
        event: "Personal Hearing Adjourned",
        authority: "Deputy Commissioner (Audit), PRA",
        referenceNo: "PRA-H-102",
        summary: "Adjourned to allow submission of original tax invoices from input suppliers.",
      },
      {
        date: "2024-03-05",
        event: "Passing of Order in Original (ONO)",
        authority: "Officer Inland Revenue (OIR), PRA",
        referenceNo: "PRA-ONO-41/2024",
        summary: "Demand of 18.5M confirmed along with 5% penalty.",
      },
      {
        date: "2024-04-02",
        event: "Filing of Appeal",
        authority: "Commissioner (Appeals), PRA",
        referenceNo: "PRA-AP-2024-91",
        summary: "Appeal filed with petition for stay on recovery. Stay granted.",
      },
    ],
    updatedAt: "2024-04-05T12:00:00Z",
    sourceFiles: ["SCN_PRA_Services_2023.pdf", "ONO_PRA_Demand_2024.pdf"],
  },
  {
    id: "CASE-2022-002",
    caseInfo: {
      caseId: "CASE-2022-002",
      taxpayerName: "Interloop Textile Enterprises",
      ntn: "0814920-5",
      strn: "0305081492015",
      taxPeriod: "Tax Year 2022",
      taxType: "Income Tax",
      relevantLegalSections: "Section 122(5A) & Section 122(9) of Income Tax Ordinance 2001",
      authorityForum: "Appellate Tribunal Inland Revenue (ATIR)",
      documentType: "Order in Appeal (OIA)",
      referenceNumber: "FBR-OIA-CIR/1922-2023",
      documentDate: "2023-08-20",
    },
    financialInfo: {
      taxDemand: 45000000,
      penalty: 2250000,
      defaultSurcharge: 3800000,
      refundAmount: 0,
      totalExposure: 51050000,
    },
    proceedingsInfo: {
      dateOfNotice: "2022-10-12",
      dateOfReply: "2022-11-05",
      hearingDates: ["2022-12-01", "2023-03-10", "2023-05-18"],
      orderDate: "2023-05-30",
      appealDate: "2023-06-25",
      decisionDate: "2023-08-20",
      currentStage: "Appellate Tribunal Appeal Pending",
    },
    outcomeInfo: {
      departmentPosition: "Disallowed major yarn manufacturing raw-material purchases, claiming payments bypassed banking channels under section 21(l).",
      taxpayerPosition: "Payments were made via crossed cheques as verified by clearing receipts. Tax officer erred by ignoring banking ledger corroboration.",
      decisionSummary: "Commissioner (Appeals) partially accepted taxpayer record. PKR 30M purchases deleted, PKR 15M purchases remanded back for physical audit verification.",
      reliefGranted: "Substantial partial relief. PKR 30M raw purchase demand dropped.",
      amountConfirmed: 15000000,
      amountDeleted: 30000000,
      amountRemanded: 15000000,
      currentStatus: "Under Review / Remand Ongoing",
    },
    chronology: [
      {
        date: "2022-10-12",
        event: "Audit Notice Section 122(9)",
        authority: "Unit-04, Large Taxpayers Office (LTO) Lahore",
        referenceNo: "FBR-AUD-ITY-2022",
        summary: "Intimation of audit and query list regarding section 21(l) banking channels.",
      },
      {
        date: "2022-11-05",
        event: "Submission of Reconciliation & Bank Ledgers",
        authority: "Tax Advisory Office Interloop",
        referenceNo: "IL-FBR/RECON-02",
        summary: "Submitted bank statements and clearing memos.",
      },
      {
        date: "2023-05-30",
        event: "Assessment Order Section 122(5A)",
        authority: "Deputy Commissioner Inland Revenue (DCIR)",
        referenceNo: "FBR-IR-ONO-108-2023",
        summary: "DCIR disallowed bank entries, raising PKR 45M demand and 2.25M penalty.",
      },
      {
        date: "2023-06-25",
        event: "Filing of Appeal with CIR(A)",
        authority: "Commissioner Inland Revenue (Appeals), Zone-1",
        referenceNo: "CIRA-APP-G76",
        summary: "Contested ONO-108, presenting cross cheque registers.",
      },
      {
        date: "2023-08-20",
        event: "Hearing and Order in Appeal (OIA)",
        authority: "Commissioner Inland Revenue (Appeals)",
        referenceNo: "OIA-Zone1-FBR-1922-2023",
        summary: "CIR(A) accepted appeal arguments for PKR 30M of demand and remanded PKR 15M.",
      },
    ],
    updatedAt: "2023-08-25T14:30:00Z",
    sourceFiles: ["ONO_disallowance_3001.pdf", "OIA_CIR_Appeals_Zone_1.pdf"],
  },
  {
    id: "CASE-2024-003",
    caseInfo: {
      caseId: "CASE-2024-003",
      taxpayerName: "Chenab Textile Corporation",
      ntn: "0342981-2",
      strn: "0302034298112",
      taxPeriod: "Tax Year 2021",
      taxType: "Customs Duty",
      relevantLegalSections: "Section 32, Section 83 of the Customs Act 1969",
      authorityForum: "Appellate Tribunal Customs, Lahore",
      documentType: "High Court Judgment",
      referenceNumber: "HC-WP-1920/2024",
      documentDate: "2025-01-10",
    },
    financialInfo: {
      taxDemand: 8200000,
      penalty: 410000,
      defaultSurcharge: 1100000,
      refundAmount: 0,
      totalExposure: 9710000,
    },
    proceedingsInfo: {
      dateOfNotice: "2021-04-18",
      dateOfReply: "2021-05-15",
      hearingDates: ["2021-06-05", "2022-02-12"],
      orderDate: "2022-04-10",
      appealDate: "2022-05-20",
      decisionDate: "2025-01-10",
      currentStage: "Concluded with Full Relief",
    },
    outcomeInfo: {
      departmentPosition: "Alleged under-valuation of imported machinery spare parts under customs rule-9, applying high baseline price catalog.",
      taxpayerPosition: "Machinery was imported from OEM in Germany on real contract rates. Historical valuation ruling exists for same equipment model.",
      decisionSummary: "Lahore High Court accepted Writ Petition, declared custom valuation department reassessment void, and quashed additional customs duty demand.",
      reliefGranted: "Full relief granted. PKR 8.2M duty and penalty completely deleted.",
      amountConfirmed: 0,
      amountDeleted: 8200000,
      amountRemanded: 0,
      currentStatus: "Closed",
    },
    chronology: [
      {
        date: "2021-04-18",
        event: "Seizure & Re-assessment SCN",
        authority: "Collectorate of Customs Appraisement East, Karachi",
        referenceNo: "CUST-SCN-7881",
        summary: "Customs department disputed transaction value of textile weaving gear.",
      },
      {
        date: "2022-04-10",
        event: "Customs ONO Passed",
        authority: "Assistant Collector Customs, Karachi",
        referenceNo: "CUST-ONO-92",
        summary: "Confirmed differential customs duty of 8.2M + 0.41M fine.",
      },
      {
        date: "2022-05-20",
        event: "Appeal filed with Customs Tribunal",
        authority: "Appellate Tribunal Custom Enforcement",
        referenceNo: "CUST-TRB-41",
        summary: "Contested revaluation. Stay on recovery pending tribunal decision.",
      },
      {
        date: "2023-10-15",
        event: "Tribunal Rejected Appeal",
        authority: "Customs Tribunal Lahore Bench",
        referenceNo: "CUST-TRB-ORDER-122",
        summary: "Tribunal upheld the valuation increase. Recovery notices imminent.",
      },
      {
        date: "2024-11-20",
        event: "Writ Petition and LHC Stay",
        authority: "Honorable Lahore High Court",
        referenceNo: "HC-WP-1920/2024",
        summary: "Filed constitutional writ against arbitrary tribunal endorsement of rule-9, stay issued.",
      },
      {
        date: "2025-01-10",
        event: "LHC Final Judgment",
        authority: "Lahore High Court Bench",
        referenceNo: "LHC-CIVIL-JUD-1920",
        summary: "Court quashed appraisal demand, upholding OEM transaction invoice as sole legal value.",
      },
    ],
    updatedAt: "2025-01-12T10:00:00Z",
    sourceFiles: ["Customs_Writ_WP1920.pdf", "LHC_Judgment_Sparing.pdf"],
  }
];
